version: '3.7'

services:
  komizer:
    image: mlabouardy/komiser:latest
    container_name: komizer
    ports:
      - '3000:3000'
    command:
      - '-d'
      - '0'
      - '-r'
      - 'redis:6379'
      - '-m'
    volumes:
      - '${PWD}/.aws:/${HOME}/.aws'
    links:
      - redis

  redis:
    image: redis:6.2.6
    container_name: redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6379" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    # restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  redis_data:
    driver: local
