---
'**/*.{go,py,css,html,js,json,md,yaml,yml,xml}':
    - npx prettier --write .

'**/*.js':
    - npx eslint --no-eslintrc --cache --fix

'**/*.py':
    - black --verbose
    - pylint

'**/*.sh':
    - shellcheck

'**/*.robot':
    - robotidy
