name: Release AWS Cost Hub Code

on:
  push:
    tags:
    - '*'
    branches: [ main, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "aws-cost-hub/aws-cli/*.sh,aws-cost-hub/cost-explorer/libs/*.py,aws-cost-hub/cost-explorer/*.py,iam/iam/cloudsplaining.sh"
        token: ${{ secrets.GITHUB_TOKEN }}
