name: Docker Image CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  IMAGE_NAME: rajasoun/aws-toolz
  VERSION: 1.0.1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install devcontainer-cli
        run: npm install @vscode/dev-container-cli

      - name: Checkout Code Base
        uses: actions/checkout@v3

      - name: Zip aws-cost-hub directory
        uses: montudor/action-zip@v1
        run: zip -qq -r aws-cost-hub.zip aws-cost-hub

      - name: Build devcontainer Docker image
        run: npx @vscode/dev-container-cli build --image-name $IMAGE_NAME:$VERSION

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "aws-cost-hub.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
